Vagrant.configure("2") do |config|
  config.vm.define :host1 do |host1|
    host1.vm.box = "ubuntu/trusty64"
    host1.vm.network :private_network, ip: "10.0.0.10"
    host1.vm.hostname = "host1"
  end

  config.vm.define :host2 do |host2|
    host2.vm.box = "ubuntu/trusty64"
    host2.vm.network :private_network, ip: "10.0.0.11"
    host2.vm.hostname = "host2"
  end

  config.vm.define :host3 do |host3|
    host3.vm.box = "ubuntu/trusty64"
    host3.vm.network :private_network, ip: "10.0.0.12"
    host3.vm.hostname = "host3"
  end

  config.vm.define :host4 do |host4|
    host4.vm.box = "ubuntu/trusty64"
    host4.vm.network :private_network, ip: "10.0.0.13"
    host4.vm.hostname = "host4"
  end
end