Vagrant.configure(2) do |config|  
  config.vm.define "dh1" do |dh1|
    dh1.vm.box = "ubuntu/trusty64"
    dh1.vm.hostname = "dh1"

    dh1.vm.network "forwarded_port", guest: 3000, host: 3000

    dh1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "dh2" do |dh2|
    dh2.vm.box = "ubuntu/trusty64"
    dh2.vm.hostname = "dh1"

    dh2.vm.network "forwarded_port", guest: 4000, host: 4000

    dh2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end
end
